# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yadullahd/Projects/pgm-image-processing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yadullahd/Projects/pgm-image-processing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yadullahd/Projects/pgm-image-processing/CMakeFiles /Users/yadullahd/Projects/pgm-image-processing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yadullahd/Projects/pgm-image-processing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named p3

# Build rule for target.
p3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p3
.PHONY : p3

# fast build rule for target.
p3/fast:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/build
.PHONY : p3/fast

#=============================================================================
# Target rules for targets named p4

# Build rule for target.
p4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p4
.PHONY : p4

# fast build rule for target.
p4/fast:
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/build
.PHONY : p4/fast

#=============================================================================
# Target rules for targets named p2

# Build rule for target.
p2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p2
.PHONY : p2

# fast build rule for target.
p2/fast:
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/build
.PHONY : p2/fast

#=============================================================================
# Target rules for targets named p1

# Build rule for target.
p1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p1
.PHONY : p1

# fast build rule for target.
p1/fast:
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/build
.PHONY : p1/fast

# target to build an object file
src/p1.o:
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/p1.o
.PHONY : src/p1.o

# target to preprocess a source file
src/p1.i:
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/p1.i
.PHONY : src/p1.i

# target to generate assembly for a file
src/p1.s:
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/p1.s
.PHONY : src/p1.s

# target to build an object file
src/p2.o:
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/p2.o
.PHONY : src/p2.o

# target to preprocess a source file
src/p2.i:
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/p2.i
.PHONY : src/p2.i

# target to generate assembly for a file
src/p2.s:
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/p2.s
.PHONY : src/p2.s

# target to build an object file
src/p3.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/p3.o
.PHONY : src/p3.o

# target to preprocess a source file
src/p3.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/p3.i
.PHONY : src/p3.i

# target to generate assembly for a file
src/p3.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/p3.s
.PHONY : src/p3.s

# target to build an object file
src/p4.o:
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/p4.o
.PHONY : src/p4.o

# target to preprocess a source file
src/p4.i:
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/p4.i
.PHONY : src/p4.i

# target to generate assembly for a file
src/p4.s:
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/p4.s
.PHONY : src/p4.s

# target to build an object file
src/pgm.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/pgm.o
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/pgm.o
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/pgm.o
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/pgm.o
.PHONY : src/pgm.o

# target to preprocess a source file
src/pgm.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/pgm.i
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/pgm.i
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/pgm.i
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/pgm.i
.PHONY : src/pgm.i

# target to generate assembly for a file
src/pgm.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/pgm.s
	$(MAKE) -f CMakeFiles/p4.dir/build.make CMakeFiles/p4.dir/src/pgm.s
	$(MAKE) -f CMakeFiles/p2.dir/build.make CMakeFiles/p2.dir/src/pgm.s
	$(MAKE) -f CMakeFiles/p1.dir/build.make CMakeFiles/p1.dir/src/pgm.s
.PHONY : src/pgm.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... p3"
	@echo "... edit_cache"
	@echo "... p4"
	@echo "... p2"
	@echo "... p1"
	@echo "... src/p1.o"
	@echo "... src/p1.i"
	@echo "... src/p1.s"
	@echo "... src/p2.o"
	@echo "... src/p2.i"
	@echo "... src/p2.s"
	@echo "... src/p3.o"
	@echo "... src/p3.i"
	@echo "... src/p3.s"
	@echo "... src/p4.o"
	@echo "... src/p4.i"
	@echo "... src/p4.s"
	@echo "... src/pgm.o"
	@echo "... src/pgm.i"
	@echo "... src/pgm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

